---
- hosts: all
  ignore_errors: yes
  become: yes
  tasks:
   - name: create user
     user:
        name: Banke
        comment: Banke Banks
  
   - name: create directory
     file:
        path: /tmp/devop-ans
        owner: Banke
        state: directory
        mode: "0777"
   
   - name: create file
     file:
        path: /tmp/ansible-ans
        owner: Banke
        state: touch
        mode: "0600"

